default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

development:
  forest_env_secret: 224191aa620305780adef1d3ca6d8607151f24d98f6075984ad9da1221da6e25
  forest_auth_secret: N9SRFpjDgmRUKKNlysr2Kw
  <<: *default
test:
  <<: *default
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  <<: *default
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  <<: *default
